import Head from 'next/head'
import Link from 'next/link';
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  console.log("[HomePage] render");

  return (
    <div>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 align="center">Home page</h1>

      <div className={styles.posts}>
        <h5>Blogs</h5>
        <ul>
          <li>
            <Link href="/posts/1"><a>1st post</a></Link>
          </li>
          <li>
            <Link href="/posts/2"><a>2nd post</a></Link>
          </li>
          <li>
            <Link href="/posts/3"><a>3rd post</a></Link>
          </li>
        </ul>

      </div>
    </div>
  )
}
